### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zinking** [bing-ads-sdk/BingAds-Java-SDK#2]
/**
     * Reads the next csv row values, creates a new instance of the object and
     * populates it with the row values
     *
     * @returns>Next {@link BulkObject}
     */
    @Override
    public BulkObject readNextBulkObject() {
        this.initializeHeadersIfNeeded(); //# is this really need to be called at every retrieval?

        if (!objectIterator.hasNext()) {
            return null;
        }

        String[] fields = objectIterator.next();

        RowValues values = new RowValues(fields, columnMapping);
        BulkObject obj = bulkObjectFactory.createBulkObject(values);
        obj.readFromRowValues(values);//#why not combine the call with above?

        return obj;
    }

**Comment by dennis-yemelyanov** [comment]
Thank you for your feedback!

initializeHeadersIfNeeded is a very lightweight method and will read headers only once, so calling it on every read operation shouldn't be an issue. Please let us know if you think otherwise.

The idea behind BulkObjectFactory is to have a mapper between the row Type in the bulk file and a corresponding Java object type. To keep things simple, it only creates a new object instance. Populating the object with actual values is a responsibility of BulkObjectReader (populates with values from the same row) and BulkStreamReader (populates with data from additional rows, such as error rows).

**Comment by zinking** [comment]
I understand your point.

I know this is really a trivial call here, but it is still a method call which will be used in the main bulk loop ( might contain billions of keywords).  Most importantly, I don't see why it is needed to initialise upon every line retrieval. it should be initialised only on the first line, isn't it ?

**Comment by dennis-yemelyanov** [comment]
We could do it in the constructor, but usually it's a good design practice to only do minimal required work in the constructor. Accessing a file is thousand times slower than calling a method, so having this line in the loop shouldn't affect reading performance.
